rd_seed: 1
n_cls: 6
resolution: 64
ds_rate: 2
mode: epoch
max_epoch : 60
num_mini_batch_per_epoch: 5000
num_patches: 15

optimizer:
  type : Adam
  lr   : 0.001
  betas: [0.5, 0.999]
  eps  : 0.000001
  weight_decay: 0


lr_scheduler:
  type: WarmupCosineLR
  max_iters: 200000
  warmup_factor: 0.001
  warmup_iters: 2000

loss:
  vp_weight: 100.0
  t_weight: 1.0
  s_weight: 1.0

train_dataset:
  data_dir: ../../../data/NOCS
  sample_num: 2048
  random_rotate: True
  angle_range: 20

train_dataloader:
  bs: 48
  num_workers: 16
  shuffle: True
  drop_last: True
  pin_memory: False

test:
  sample_num: 2048
  data_dir: ../../data/NOCS

feature:
  feature_path: save_feature
  ref_feature_file: reference_feature.npy
per_val: 10
per_write: 50
